apiVersion: apps/v1 
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: webapptest                    # Name of the Kubernetes resource
  labels:
    app: webapptest
spec:
  replicas: 1                                     # Number of pods to run at any given time
  selector:
    matchLabels: 
      app: webapptest                 # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: webapptest
    spec:                                         # Spec for the container which will run in the Pod
      containers:
      - name: webapptest 
        image: bnn987654321/webapptest:latest		  # The image we are getting from dockerhub
        imagePullPolicy: Always             # If we have not pulled it before, get it from dockerhub
        ports:
          - name: http
            containerPort: 80                     # Should match the port number that the Go application listens on
