apiVersion: v1  
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: webapptest                   # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: webapptest
spec:
  type: NodePort                              # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: webapptest                  # Selects any Pod with labels `app=fullstack-app-postgres`
  ports: 
  - name: http
    port: 80
    targetPort: 80