name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u bnn987654321 -p yali1114
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bnn987654321/webapptest:$(date +%s)
    - name: Docker Push
      run: docker push bnn987654321/webapptest:$(date +%s)
    - name: Check Docker image
      run: docker images
